/**
 * Build zh-e2e-console-hex.mjs and MockE2eConsole.vue (ASCII-only source, \u escapes).
 * Run: node scripts/_build_e2e_console.mjs
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, '..')

const S = {
  openPlatform: '\u5f00\u653e\u5e73\u53f0',
  featureOverview: '\u529f\u80fd\u603b\u89c8',
  mockLab: 'Mock \u8054\u8c03',
  consoleTitle: '\u5168\u6d41\u7a0b\u8054\u8c03\u63a7\u5236\u53f0',
  noAdminKey: '\u672a\u914d\u7f6e Admin Key',
  adminKeyHint:
    '\u8bf7\u5728 window.conf \u914d\u7f6e VUE_APP_OPEN_API_ADMIN_KEY\u3002' +
    'Admin \u7ba1\u7406\u8d70 /open-api-service \u5e73\u53f0\u7f51\u5173\uff1b' +
    'Token \u4e0e Open API \u8d70 partner-gateway\uff08\u540c\u6e90 nginx/dev \u53cd\u4ee3\u81f3 35770\uff0c\u6216\u914d\u7f6e VUE_APP_OPEN_PARTNER_GATEWAY_URL \u76f4\u8fde\uff09\u3002',
  pageTitle: 'Manual Mock \u5168\u6d41\u7a0b\u8054\u8c03',
  pageDesc:
    '\u8986\u76d6\u811a\u672c e2e-mock-manual-flow + e2e-full-flow \u6838\u5fc3\u8def\u5f84\uff1a' +
    'Partner\u3001Token\u3001\u5efa\u4efb\u52a1(RUNNING)\u3001\u5bfc\u5165 XML\u3001FINISHED\u3001\u5b9e\u4f8b\u3001\u5916\u53d1\u3001Webhook\u3002',
  runAll: '\u4e00\u952e\u8fd0\u884c\u5168\u6d41\u7a0b',
  reset: '\u91cd\u7f6e',
  stepEnv: '\u73af\u5883',
  stepCreateTask: '\u5efa\u4efb\u52a1',
  stepImportXml: '\u5bfc\u5165 XML',
  stepVerify: '\u9a8c\u8bc1',
  stepExport: '\u5916\u53d1',
  stepFsm: '\u72b6\u6001\u673a',
  paramsTitle: '\u8054\u8c03\u53c2\u6570',
  partnerIdLabel: 'partnerId\uff08\u81ea\u52a8\u524d\u7f00 e2e-\uff09',
  partnerPlaceholder: '\u7559\u7a7a\u5219\u4f7f\u7528\u65f6\u95f4\u6233',
  taskName: '\u4efb\u52a1\u540d\u79f0',
  scanTargets: '\u626b\u63cf\u76ee\u6807 hosts',
  targetsPlaceholder: '\u9017\u53f7\u5206\u9694 IP',
  xmlLabel: 'NSFocus XML \u62a5\u544a\uff08\u5168\u6d41\u7a0b\u5fc5\u586b\uff09',
  pickXml: '\u9009\u62e9 XML',
  includeFsm:
    '\u5305\u542b\u5b9e\u4f8b\u72b6\u6001\u673a\uff08\u6838\u9a8c\u3001\u4fee\u590d\u3001\u4fee\u590d\u6838\u9a8c + VERIFY_FIX \u5916\u53d1\uff09',
  exportWaitSec: '\u5916\u53d1\u7b49\u5f85\u79d2\u6570',
  sessionTitle: '\u5f53\u524d\u4f1a\u8bdd',
  goManual: '\u534a\u4eba\u5de5\u5bfc\u5165\u9875',
  goWebhook: 'Webhook \u65e5\u5fd7',
  goInvocation: '\u8c03\u7528\u8bb0\u5f55',
  stepExec: '\u5206\u6b65\u6267\u884c',
  s1: '1 \u5065\u5eb7',
  s4: '4 \u5efa\u4efb\u52a1',
  s5: '5 \u5bfc\u5165',
  s6: '6 \u9a8c\u8bc1',
  s7: '7 \u5916\u53d1',
  resultTitle: '\u6267\u884c\u7ed3\u679c',
  lastRun: '\u6700\u8fd1\u8fd0\u884c\uff1a',
  emptyHint: '\u70b9\u51fb\u300c\u4e00\u952e\u8fd0\u884c\u5168\u6d41\u7a0b\u300d\u6216\u5206\u6b65\u6309\u94ae\u5f00\u59cb',
  tpl1002: '1002 \u5b58\u6d3b',
  tpl1003: '1003 \u7aef\u53e3',
  tpl1001: '1001 \u6f0f\u6d1e',
  summaryDone: '\u5b8c\u6210',
  summaryFail: '\u5931\u8d25',
  summaryStep: '\u6b65',
  summaryAll: '\u5168\u90e8',
  summaryPass: '\u6b65\u901a\u8fc7',
  pickXmlWarn: '\u8bf7\u9009\u62e9 .xml \u6587\u4ef6',
  resetInfo: '\u5df2\u91cd\u7f6e\u8054\u8c03\u4f1a\u8bdd',
  configAdmin: '\u8bf7\u5148\u914d\u7f6e VUE_APP_OPEN_API_ADMIN_KEY',
  needXml: '\u5168\u6d41\u7a0b\u9700\u8981\u5148\u9009\u62e9 NSFocus XML \u62a5\u544a',
  flowFail: '\u5168\u6d41\u7a0b\u7ed3\u675f\uff0c',
  flowFailSuffix: ' \u6b65\u5931\u8d25',
  flowOk: '\u5168\u6d41\u7a0b\u8054\u8c03\u901a\u8fc7',
  needAdmin: '\u8bf7\u5148\u914d\u7f6e Admin Key',
  needPartner: '\u8bf7\u5148\u6267\u884c Partner \u6b65\u9aa4',
  needTask: '\u8bf7\u5148\u5efa\u4efb\u52a1',
  needXmlShort: '\u8bf7\u9009\u62e9 XML',
  passSuffix: ' \u901a\u8fc7'
}

function escAttr (s) {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '&quot;')
}

function escJs (s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

// --- write hex module ---
const hexLines = [
  '/** Auto-generated by scripts/_build_e2e_console.mjs */',
  'export const Z = {'
]
for (const [k, v] of Object.entries(S)) {
  hexLines.push(`  ${k}: '${Buffer.from(v, 'utf8').toString('hex')}',`)
}
hexLines.push(
  '}',
  '',
  'export function t (key) {',
  '  const hex = Z[key]',
  "  if (!hex) throw new Error('missing zh key: ' + key)",
  "  return Buffer.from(hex, 'hex').toString('utf8')",
  '}',
  ''
)
const hexPath = path.join(__dirname, 'lib/zh-e2e-console-hex.mjs')
fs.writeFileSync(hexPath, hexLines.join('\n'), 'utf8')

// --- write vue ---
const vue = `<template>
  <div class="p_16 mock-e2e-page">
    <a-breadcrumb>
      <a-breadcrumb-item>${escAttr(S.openPlatform)}</a-breadcrumb-item>
      <a-breadcrumb-item>
        <a @click="$router.push({ name: 'OpenPlatformOverview' })">${escAttr(S.featureOverview)}</a>
      </a-breadcrumb-item>
      <a-breadcrumb-item>${escAttr(S.mockLab)}</a-breadcrumb-item>
      <a-breadcrumb-item>${escAttr(S.consoleTitle)}</a-breadcrumb-item>
    </a-breadcrumb>

    <a-alert
      v-if="!adminKeyReady"
      type="warning"
      show-icon
      message="${escAttr(S.noAdminKey)}"
      description="${escAttr(S.adminKeyHint)}"
      style="margin: 16px 0;"
    />

    <a-card :bordered="false" class="e2e-header-card">
      <div class="e2e-header">
        <div>
          <h2 class="e2e-title">${escAttr(S.pageTitle)}</h2>
          <p class="e2e-desc">${escAttr(S.pageDesc)}</p>
        </div>
        <div class="e2e-header-actions">
          <a-button :loading="running" type="primary" icon="play-circle" @click="runFullFlow">
            ${escAttr(S.runAll)}
          </a-button>
          <a-button :disabled="running" @click="resetSession">${escAttr(S.reset)}</a-button>
        </div>
      </div>

      <a-steps :current="currentStep" size="small" class="e2e-steps">
        <a-step title="${escAttr(S.stepEnv)}" />
        <a-step title="Partner" />
        <a-step title="Token" />
        <a-step title="${escAttr(S.stepCreateTask)}" />
        <a-step title="${escAttr(S.stepImportXml)}" />
        <a-step title="${escAttr(S.stepVerify)}" />
        <a-step title="${escAttr(S.stepExport)}" />
        <a-step title="Webhook" />
        <a-step v-if="taskForm.includeInstanceFsm" title="${escAttr(S.stepFsm)}" />
      </a-steps>
    </a-card>

    <a-row :gutter="16">
      <a-col :xs="24" :xl="10">
        <a-card title="${escAttr(S.paramsTitle)}" :bordered="false" class="e2e-section-card">
          <a-form layout="vertical" class="e2e-form">
            <a-form-item label="${escAttr(S.partnerIdLabel)}">
              <a-input v-model="partnerSuffix" :disabled="running" placeholder="${escAttr(S.partnerPlaceholder)}" />
            </a-form-item>
            <a-form-item label="extTaskId">
              <a-input v-model="taskForm.extTaskId" :disabled="running" />
            </a-form-item>
            <a-form-item label="${escAttr(S.taskName)}">
              <a-input v-model="taskForm.taskName" :disabled="running" />
            </a-form-item>
            <a-row :gutter="12">
              <a-col :span="12">
                <a-form-item label="scanTemplateId">
                  <a-select v-model="taskForm.scanTemplateId" :disabled="running">
                    <a-select-option :value="1002">${escAttr(S.tpl1002)}</a-select-option>
                    <a-select-option :value="1003">${escAttr(S.tpl1003)}</a-select-option>
                    <a-select-option :value="1001">${escAttr(S.tpl1001)}</a-select-option>
                  </a-select>
                </a-form-item>
              </a-col>
              <a-col :span="12">
                <a-form-item label="reportTemplateId">
                  <a-select v-model="taskForm.reportTemplateId" :disabled="running">
                    <a-select-option :value="2001">2001 JSON</a-select-option>
                    <a-select-option :value="2002">2002 XML</a-select-option>
                  </a-select>
                </a-form-item>
              </a-col>
            </a-row>
            <a-form-item label="${escAttr(S.scanTargets)}">
              <a-input v-model="taskForm.targets" :disabled="running" placeholder="${escAttr(S.targetsPlaceholder)}" />
            </a-form-item>
            <a-form-item label="${escAttr(S.xmlLabel)}">
              <div class="e2e-upload-row">
                <input
                  ref="fileInput"
                  type="file"
                  accept=".xml,application/xml,text/xml"
                  class="e2e-file-input"
                  @change="onFileChange"
                />
                <a-button icon="upload" :disabled="running" @click="pickFile">${escAttr(S.pickXml)}</a-button>
                <span v-if="xmlFileName" class="e2e-file-name">{{ xmlFileName }}</span>
              </div>
            </a-form-item>
            <a-form-item>
              <a-checkbox v-model="taskForm.includeInstanceFsm" :disabled="running">
                ${escAttr(S.includeFsm)}
              </a-checkbox>
            </a-form-item>
            <a-form-item label="${escAttr(S.exportWaitSec)}">
              <a-input-number v-model="exportWaitSec" :min="10" :max="120" :disabled="running" style="width: 100%;" />
            </a-form-item>
          </a-form>

          <a-divider />

          <div class="e2e-session" v-if="session.partnerId">
            <div class="session-title">${escAttr(S.sessionTitle)}</div>
            <div class="session-row"><span>partnerId</span><code>{{ session.partnerId }}</code></div>
            <div class="session-row" v-if="session.clientId"><span>clientId</span><code>{{ session.clientId }}</code></div>
            <div class="session-row" v-if="session.taskId"><span>taskId</span><code>{{ session.taskId }}</code></div>
            <div class="session-links" v-if="session.taskId">
              <a @click="goManualIngest">${escAttr(S.goManual)}</a>
              <a-divider type="vertical" />
              <a @click="goWebhookLog">${escAttr(S.goWebhook)}</a>
              <a-divider type="vertical" />
              <a @click="goInvocations">${escAttr(S.goInvocation)}</a>
            </div>
          </div>
        </a-card>

        <a-card title="${escAttr(S.stepExec)}" :bordered="false" class="e2e-section-card" style="margin-top: 16px;">
          <a-button-group class="e2e-step-buttons">
            <a-button size="small" :disabled="running" @click="runStep('health')">${escAttr(S.s1)}</a-button>
            <a-button size="small" :disabled="running" @click="runStep('partner')">2 Partner</a-button>
            <a-button size="small" :disabled="running" @click="runStep('token')">3 Token</a-button>
            <a-button size="small" :disabled="running" @click="runStep('createTask')">${escAttr(S.s4)}</a-button>
            <a-button size="small" :disabled="running || !session.taskId" @click="runStep('import')">${escAttr(S.s5)}</a-button>
            <a-button size="small" :disabled="running || !session.taskId" @click="runStep('taskVerify')">${escAttr(S.s6)}</a-button>
            <a-button size="small" :disabled="running || !session.taskId" @click="runStep('export')">${escAttr(S.s7)}</a-button>
            <a-button size="small" :disabled="running || !session.partnerId" @click="runStep('webhook')">8 Webhook</a-button>
          </a-button-group>
        </a-card>
      </a-col>

      <a-col :xs="24" :xl="14">
        <a-card title="${escAttr(S.resultTitle)}" :bordered="false" class="e2e-section-card">
          <div class="e2e-summary" v-if="results.length">
            <a-tag :color="summaryColor">{{ summaryText }}</a-tag>
            <span class="e2e-summary-time" v-if="lastRunAt">${escAttr(S.lastRun)}{{ lastRunAt }}</span>
          </div>
          <a-empty v-if="!results.length" description="${escAttr(S.emptyHint)}" />

          <a-timeline v-else class="e2e-timeline">
            <a-timeline-item
              v-for="item in results"
              :key="item.key + item.at"
              :color="timelineColor(item.status)"
            >
              <div class="timeline-title">
                <strong>{{ item.title }}</strong>
                <enum-tag type="webhookDeliveryStatus" :value="mapStatus(item.status)" :fallback="item.status" />
              </div>
              <div class="timeline-msg">{{ item.message }}</div>
              <div v-if="item.taskId" class="timeline-extra">taskId: <code>{{ item.taskId }}</code></div>
            </a-timeline-item>
          </a-timeline>
        </a-card>
      </a-col>
    </a-row>
  </div>
</template>

<script>
import EnumTag from '@/components/openPlatform/EnumTag'
import { hasAdminKey } from '@/utils/openApiRequest'
import { clearPartnerSession } from '@/utils/openPartnerRequest'
import {
  buildRunId,
  runCreateTaskStep,
  runExportStep,
  runFullManualE2e,
  runHealthStep,
  runImportStep,
  runPartnerStep,
  runTaskVerifyStep,
  runTokenStep,
  runWebhookStep
} from '@/api/openPlatform/e2eRunner'

const MSG = {
  pickXmlWarn: '${escJs(S.pickXmlWarn)}',
  resetInfo: '${escJs(S.resetInfo)}',
  configAdmin: '${escJs(S.configAdmin)}',
  needXml: '${escJs(S.needXml)}',
  flowFail: '${escJs(S.flowFail)}',
  flowFailSuffix: '${escJs(S.flowFailSuffix)}',
  flowOk: '${escJs(S.flowOk)}',
  needAdmin: '${escJs(S.needAdmin)}',
  needPartner: '${escJs(S.needPartner)}',
  needTask: '${escJs(S.needTask)}',
  needXmlShort: '${escJs(S.needXmlShort)}',
  passSuffix: '${escJs(S.passSuffix)}',
  summaryDone: '${escJs(S.summaryDone)}',
  summaryFail: '${escJs(S.summaryFail)}',
  summaryStep: '${escJs(S.summaryStep)}',
  summaryAll: '${escJs(S.summaryAll)}',
  summaryPass: '${escJs(S.summaryPass)}'
}

export default {
  name: 'MockE2eConsole',
  components: { EnumTag },
  data () {
    const runId = buildRunId()
    return {
      runId,
      running: false,
      partnerSuffix: '',
      exportWaitSec: 45,
      xmlFile: null,
      xmlFileName: '',
      taskForm: {
        extTaskId: \`EXT-E2E-\${runId}\`,
        taskName: 'console-manual-e2e',
        type: 1,
        scanTemplateId: 1002,
        reportTemplateId: 2001,
        targets: '172.16.3.22,172.16.3.23,172.16.3.24',
        expectManualMode: true,
        includeInstanceFsm: false
      },
      session: {
        partnerId: '',
        clientId: '',
        clientSecret: '',
        accessToken: '',
        taskId: ''
      },
      results: [],
      lastRunAt: ''
    }
  },
  computed: {
    adminKeyReady () {
      return hasAdminKey()
    },
    partnerId () {
      const suffix = (this.partnerSuffix || '').trim() || buildRunId()
      return \`e2e-\${suffix}\`
    },
    currentStep () {
      if (!this.results.length) return 0
      const order = ['health', 'partner', 'token', 'createTask', 'import', 'taskVerify', 'export', 'webhook', 'instanceFsm']
      let max = 0
      this.results.forEach(r => {
        const idx = order.indexOf(r.key)
        if (idx >= 0 && r.status === 'success') max = Math.max(max, idx + 1)
      })
      return max
    },
    summaryText () {
      const errors = this.results.filter(r => r.status === 'error').length
      const ok = this.results.filter(r => r.status === 'success').length
      if (errors) return \`\${MSG.summaryDone} \${ok} \${MSG.summaryStep}\uff0c\${MSG.summaryFail} \${errors} \${MSG.summaryStep}\`
      return \`\${MSG.summaryAll} \${ok} \${MSG.summaryPass}\`
    },
    summaryColor () {
      return this.results.some(r => r.status === 'error') ? 'red' : 'green'
    }
  },
  methods: {
    pickFile () {
      const input = this.$refs.fileInput
      if (input) input.click()
    },
    onFileChange (e) {
      const file = e.target && e.target.files && e.target.files[0]
      if (!file) return
      if (!file.name.toLowerCase().endsWith('.xml')) {
        this.$message.warning(MSG.pickXmlWarn)
        return
      }
      this.xmlFile = file
      this.xmlFileName = file.name
    },
    mergeSession (result) {
      if (!result) return
      if (result.partnerId) this.session.partnerId = result.partnerId
      if (result.clientId) this.session.clientId = result.clientId
      if (result.clientSecret) this.session.clientSecret = result.clientSecret
      if (result.accessToken) this.session.accessToken = result.accessToken
      if (result.taskId) this.session.taskId = result.taskId
    },
    appendResult (result) {
      this.results.push(result)
      this.mergeSession(result)
    },
    mapStatus (status) {
      if (status === 'success') return 'SUCCESS'
      if (status === 'error') return 'FAILED'
      if (status === 'skip') return 'SKIPPED'
      return 'PENDING'
    },
    timelineColor (status) {
      if (status === 'success') return 'green'
      if (status === 'error') return 'red'
      if (status === 'skip') return 'gray'
      return 'blue'
    },
    resetSession () {
      this.results = []
      this.session = { partnerId: '', clientId: '', clientSecret: '', accessToken: '', taskId: '' }
      clearPartnerSession()
      this.runId = buildRunId()
      this.taskForm.extTaskId = \`EXT-E2E-\${this.runId}\`
      this.$message.info(MSG.resetInfo)
    },
    async runFullFlow () {
      if (!this.adminKeyReady) {
        this.$message.warning(MSG.configAdmin)
        return
      }
      if (!this.xmlFile) {
        this.$message.warning(MSG.needXml)
        return
      }
      this.running = true
      this.results = []
      try {
        const list = await runFullManualE2e({
          partnerId: this.partnerId,
          taskForm: this.taskForm,
          xmlFile: this.xmlFile,
          minInstances: 1,
          exportWaitSec: this.exportWaitSec,
          includeInstanceFsm: this.taskForm.includeInstanceFsm,
          runId: this.runId
        })
        list.forEach(r => this.appendResult(r))
        this.lastRunAt = this.formatTime(new Date())
        const failed = list.filter(r => r.status === 'error')
        if (failed.length) {
          this.$message.error(MSG.flowFail + failed.length + MSG.flowFailSuffix)
        } else {
          this.$message.success(MSG.flowOk)
        }
      } finally {
        this.running = false
      }
    },
    async runStep (key) {
      if (!this.adminKeyReady && key !== 'health') {
        this.$message.warning(MSG.needAdmin)
        return
      }
      this.running = true
      let result
      try {
        switch (key) {
          case 'health':
            result = await runHealthStep()
            break
          case 'partner':
            result = await runPartnerStep(this.partnerId)
            break
          case 'token':
            if (!this.session.clientId) {
              this.$message.warning(MSG.needPartner)
              return
            }
            result = await runTokenStep(this.session.clientId, this.session.clientSecret, this.session.partnerId || this.partnerId)
            break
          case 'createTask':
            result = await runCreateTaskStep(this.taskForm, this.session.partnerId || this.partnerId)
            break
          case 'import':
            if (!this.session.taskId) {
              this.$message.warning(MSG.needTask)
              return
            }
            if (!this.xmlFile) {
              this.$message.warning(MSG.needXmlShort)
              return
            }
            result = await runImportStep(this.session.taskId, this.xmlFile)
            break
          case 'taskVerify':
            result = await runTaskVerifyStep(this.session.taskId)
            break
          case 'export':
            result = await runExportStep(this.session.taskId, {
              expectJsonOnly: this.taskForm.reportTemplateId === 2001,
              maxWaitSec: this.exportWaitSec
            })
            break
          case 'webhook':
            result = await runWebhookStep(this.session.partnerId, this.session.taskId)
            break
          default:
            return
        }
        this.appendResult(result)
        this.lastRunAt = this.formatTime(new Date())
        if (result.status === 'success') {
          this.$message.success(result.title + MSG.passSuffix)
        } else if (result.status === 'error') {
          this.$message.error(result.message)
        }
      } finally {
        this.running = false
      }
    },
    goManualIngest () {
      this.$router.push({ name: 'MockManualIngest', query: { taskId: this.session.taskId } })
    },
    goWebhookLog () {
      this.$router.push({
        name: 'WebhookDeliveryList',
        query: { partnerId: this.session.partnerId, resourceId: this.session.taskId }
      })
    },
    goInvocations () {
      this.$router.push({
        name: 'InvocationList',
        query: { partnerId: this.session.partnerId, resourceId: this.session.taskId }
      })
    },
    formatTime (d) {
      return this.$moment ? this.$moment(d).format('YYYY-MM-DD HH:mm:ss') : d.toISOString()
    }
  }
}
</script>

<style scoped>
.mock-e2e-page {
  background: #f0f2f5;
  min-height: 100%;
}

.e2e-header-card,
.e2e-section-card {
  margin-top: 16px;
}

.e2e-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 16px;
  flex-wrap: wrap;
}

.e2e-title {
  margin: 0 0 8px;
  font-size: 20px;
}

.e2e-desc {
  margin: 0;
  color: rgba(0, 0, 0, 0.55);
  font-size: 13px;
  line-height: 1.6;
  max-width: 720px;
}

.e2e-header-actions {
  display: flex;
  gap: 8px;
  flex-shrink: 0;
}

.e2e-steps {
  margin-top: 20px;
}

.e2e-form :deep(.ant-form-item) {
  margin-bottom: 12px;
}

.e2e-upload-row {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
}

.e2e-file-input {
  display: none;
}

.e2e-file-name {
  font-size: 13px;
  color: rgba(0, 0, 0, 0.65);
}

.e2e-session {
  font-size: 13px;
}

.session-title {
  font-weight: 500;
  margin-bottom: 8px;
}

.session-row {
  display: flex;
  gap: 8px;
  margin-bottom: 6px;
  align-items: baseline;
}

.session-row span {
  color: rgba(0, 0, 0, 0.45);
  min-width: 72px;
}

.session-row code,
.timeline-extra code {
  color: rgba(0, 0, 0, 0.85);
  background: #f5f5f5;
  border: 1px solid #e8e8e8;
  padding: 0 4px;
  border-radius: 2px;
  font-size: 12px;
  word-break: break-all;
}

.session-links {
  margin-top: 10px;
}

.e2e-step-buttons {
  display: flex;
  flex-wrap: wrap;
}

.e2e-summary {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 16px;
}

.e2e-summary-time {
  font-size: 12px;
  color: rgba(0, 0, 0, 0.45);
}

.timeline-title {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 4px;
}

.timeline-msg {
  color: rgba(0, 0, 0, 0.65);
  font-size: 13px;
}

.timeline-extra {
  margin-top: 4px;
  font-size: 12px;
}
</style>
`

const vuePath = path.join(root, 'src/views/openPlatform/MockE2eConsole.vue')
fs.writeFileSync(vuePath, vue, 'utf8')

// verify
for (const [k, expected] of Object.entries(S)) {
  const hex = Buffer.from(expected, 'utf8').toString('hex')
  const decoded = Buffer.from(hex, 'hex').toString('utf8')
  if (decoded !== expected) throw new Error('verify failed: ' + k)
}

console.log('OK:', vuePath)
console.log('OK:', hexPath)
